model:
    in_channels: 3
    latent_dim: 128
    embedding_dim: 64
    num_embeddings: 512
    commitment_cost: 0.25

training:
    batch_size: 128
    num_epochs: 1
    learning_rate: 0.0001

dataset:
    path: /data

logging:
    log_file: logs/file.log

output:
    model_dir: /models
