model:
    in_channels: 3
    hidden_channels: 128
    embedding_dim: 64
    num_embeddings: 512
    commitment_cost: 0.25

training:
    batch_size: 128
    num_epochs: 1
    learning_rate: 0.0001

dataset:
    path: /data

output:
    model_dir: ./models
